### ISSUE TITLE
Markers disappearing on low zoom levels

### ISSUE THREAD

**Issue by anoff** [OpenMined/Team-Map#9]
When zooming into the map the markers suddenly disappear. This used to work for me.

macOS 10.12.6 (16G29) on a MacBook 2017
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

![](http://g.recordit.co/pv5EvGSHy7.gif)

**Comment by 4mber** [comment]
It was just an issue with the last dataset update. Fixed now!
